//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFCAppDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        public virtual Role RoleFK { get; set; }
    }
}
